In [1]:
#Q2
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [28]:
driver = webdriver.Chrome()

driver.get("http://www.bcci.tv/")

In [29]:
search=driver.find_element(By.XPATH, "/html/body/nav/div[1]/div[2]/ul[1]/li[2]")
search.click()

In [54]:
try:
    match=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    matcht=[]
    for i in match:
        matcht.append(i.text)
except NoSuchElementException:
    matcht.append('-')
try:
    series=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    seriest=[]
    for i in series:
        seriest.append(i.text)
except NoSuchElementException:
    seriest.append('-')
try:
    place=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
    placet=[]
    for i in place:
        placet.append(i.text)
except NoSuchElementException:
    placet.append('-')
    
try:
    time=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    timet=[]
    for i in time:
        timet.append(i.text)
except NoSuchElementException:
    timet.append('-')

In [55]:
df=pd.DataFrame({
    'Match title':matcht,'Series':seriest,'Place':placet,'Time':timet
})
df

,Match title,Series,Place,Time
0,2nd T20I -,INDIA TOUR OF IRELAND 2023,"The Village,",7:30 PM IST
1,3rd T20I -,INDIA TOUR OF IRELAND 2023,"The Village,",7:30 PM IST
2,1st ODI -,ASIA CUP 2023,"Pallekele International Cricket Stadium,",10:00 AM IST
3,2nd ODI -,ASIA CUP 2023,"Pallekele International Cricket Stadium,",10:00 AM IST
4,1st ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,",1:30 PM IST
5,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Holkar Cricket Stadium,",1:30 PM IST
6,3rd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium,",1:30 PM IST
7,1st ODI -,ICC MENS WORLD CUP 2023,"MA Chidambaram Stadium,",2:00 PM IST

In [56]:
#Q3
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [57]:
driver = webdriver.Chrome()

driver.get("http://statisticstimes.com/")

In [60]:
search=driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div[2]/div[2]/button")
search.click()
search=driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
search.click()
search=driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
search.click()

In [122]:
rankt=[]
statet= []
GSDP8t=[]
GSDP9t=[]
sharet=[]
GDPt=[]

In [123]:
try:
    rank = driver.find_elements(By.XPATH,'//td[@class="data1"]')
    for i in rank[0:33]:
        rankt.append(i.text)
except NoSuchElementException:
    rankt.append('-')
try:
    state = driver.find_elements(By.XPATH,'//td[@class="name"]')
    for i in state[0:33]:
        statet.append(i.text)
except NoSuchElementException:
    statet.append('-')        
try:
    GSDP8 = driver.find_elements(By.XPATH,'//td[@class="data sorting_1"]')
    for i in GSDP8[0:33]:
        GSDP8t.append(i.text)
except NoSuchElementException:
    GSDP8t.append('-')
try:
    GSDP9 = driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[3]')
    for i in GSDP9[0:33]:
        GSDP9t.append(i.text)
except NoSuchElementException:
    GSDP9t.append('-')
try:
    share = driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[5]')
    for i in share[0:33]:
        sharet.append(i.text)
except NoSuchElementException:
    sharet.append('-')
try:
    GDP = driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[6]')
    for i in GDP[0:33]:
        GDPt.append(i.text)
except NoSuchElementException:
    GDPt.append('-')

In [126]:
df=pd.DataFrame({
    'Rank':rankt,'State':statet,'GSDP 18-19':GSDP8t,'GSDP 19-20':GSDP9t,'Share 18-19':sharet,'GDP 2019':GDPt
})
df

,Rank,State,GSDP 18-19,GSDP 19-20,Share 18-19,GDP 2019
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,687,818",8.39%,240.726
2,3,Uttar Pradesh,"1,584,764","1,631,977",7.91%,226.806
3,4,Gujarat,"1,502,899","1,020,989",4.99%,143.179
4,5,Karnataka,"1,493,127","969,604",4.56%,130.791
5,6,West Bengal,"1,089,898",-,4.14%,118.733
6,7,Rajasthan,"942,586","831,610",3.89%,111.519
7,8,Andhra Pradesh,"862,957","574,760",2.79%,79.957
8,9,Telangana,"861,031",-,1.67%,47.982
9,10,Madhya Pradesh,"809,592","328,598",1.57%,45.145
10,11,Kerala,"781,653",-,0.83%,23.690
11,12,Delhi,"774,870","80,449",0.39%,11.115
12,13,Haryana,"734,163",-,0.22%,6.397
13,14,Bihar,"530,363","36,572",0.18%,5.086
14,15,Punjab,"526,376","31,790",0.15%,4.233
15,16,Odisha,"487,805",-,0.13%,3.737
16,17,Assam,"315,881",-,-,-
17,18,Chhattisgarh,"304,063",-,13.97%,-
18,19,Jharkhand,"297,204","1,495,758",8.41%,"1,015,735"
19,20,Uttarakhand,"245,895",-,7.92%,-
20,21,Jammu & Kashmir,"155,956","916,014",5.06%,"630,693"
21,22,Himachal Pradesh,"153,845","875,429",4.65%,"595,605"
22,23,Goa,"73,170",-,4.24%,-
23,24,Tripura,"49,845","755,790",3.99%,"514,983"
24,25,Chandigarh,"42,114","517,521",2.83%,"374,015"
25,26,Puducherry,"34,433",-,1.69%,-
26,27,Meghalaya,"33,481","288,041",1.60%,"210,837"
27,28,Sikkim,"28,723","143,063",0.80%,"107,171"
28,29,Manipur,"27,870","72,181",0.40%,"56,810"
29,30,Nagaland,"27,283",-,0.22%,-
30,31,Arunachal Pradesh,"24,603","32,833",0.18%,"23,564"
31,32,Mizoram,"22,287","28,391",0.15%,"17,060"
32,33,Andaman & Nicobar Islands,-,-,0.13%,-

In [159]:
#Q4
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [160]:
driver = webdriver.Chrome()

driver.get("https://github.com/")

In [161]:
search=driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
search.click()
search=driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a")
search.click()

In [183]:
repot=[]
repodt=[]
contrt=[] 
langt=[]

In [184]:
try:
    repo = driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a')
    for i in repo:
        repot.append(i.text)
except NoSuchElementException:
    repot.append('-')
try:
    repod = driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in repod:
        repodt.append(i.text)
except NoSuchElementException:
    repodt.append('-')
try:
    lang = driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]/span[2]')
    for i in lang:
        langt.append(i.text)
except NoSuchElementException:
    langt.append('-')
try:
    contr = driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/span[2]')
    for i in contr:
        contrt.append(i.text)
except NoSuchElementException:
    contrt.append('-')

In [ ]:
df=pd.DataFrame({'Repositery':repot, 'Repo Disc':repod,'language':langt, 'Contributors':contrt})
df

In [2]:
#Q7
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [3]:
driver = webdriver.Chrome()

driver.get("http://www.imdb.com/list/ls095964455/")

In [31]:
namet=[] 
yearst=[]
genret=[]
runt=[] 
rtingt=[] 
votest=[]

In [32]:
try:
    name = driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
    for i in name:
        namet.append(i.text)
except NoSuchElementException:
    namet.append('-')
try:
    years = driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
    for i in years:
        yearst.append(i.text)
except NoSuchElementException:
    yearst.append('-')
try:
    genre = driver.find_elements(By.XPATH,'//span[@class="genre"]')
    for i in genre:
        genret.append(i.text)
except NoSuchElementException:
    genret.append('-')
try:
    run = driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
    for i in run:
        runt.append(i.text)
except NoSuchElementException:
    runt.append('-')
try:
    rating = driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')
    for i in rating:
        rtingt.append(i.text)
except NoSuchElementException:
    rtingt.append('-')
try:
    votes = driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]')
    for i in votes:
        votest.append(i.text)
except NoSuchElementException:
    votest.append('-')

In [33]:
print(len(namet),len(yearst),len(genret),len(runt),len(rtingt),len(votest))

100 100 100 100 100 100

In [35]:
df=pd.DataFrame({'Name':namet,'Year Span':yearst,'Genre':genret,'Run Time':runt,'Ratings':rtingt,'Votes':votest})
df

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,194,121"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,267,736"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,041,440"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"306,101"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"265,174"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"52,470"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,490"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"210,188"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,706"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"263,865"

In [36]:
#Q8
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [37]:
driver = webdriver.Chrome()

driver.get("https://archive.ics.uci.edu/")

In [38]:
search=driver.find_element(By.XPATH, "/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
search.click()

In [56]:
datant=[]
datat=[]
taskt=[]
attrt=[] 
inst=[]
nattrt=[]
yeart=[]

In [57]:
try:
    datan = driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in datan:
        datant.append(i.text)
except NoSuchElementException:
    datant.append('-')
try:
    type = driver.find_elements(By.XPATH,'//div[@class="col-span-3 flex items-center gap-2"][3]/span')
    for i in type:
        datat.append(i.text)
except NoSuchElementException:
    datat.append('-')

In [58]:
print(len(datant),len(datat))

10 9

In [44]:
df=pd.DataFrame({'Data Name':datant})
df

                              Data Name
0                                  Iris
1                         Heart Disease
2                                 Adult
3                      Dry Bean Dataset
4                              Diabetes
5                                  Wine
6  Breast Cancer Wisconsin (Diagnostic)
7                        Car Evaluation
8            Rice (Cammeo and Osmancik)
9                              Mushroom

In [59]:
#Q5
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [60]:
driver = webdriver.Chrome()

driver.get("https://www.billboard.com/")

In [61]:
search=driver.find_element(By.XPATH, "/html/body/div[3]/div[9]/div/div/div/ul/li[1]/h3")
search.click()
search=driver.find_element(By.XPATH, "/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]")
search.click()

In [95]:
songt=[]
artit=[]
larat=[] 
perant=[] 
webot=[]

In [90]:
try:
    name = driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li/h3')
    for i in name:
        songt.append(i.text)
except NoSuchElementException:
    songt.append('-')
try:
    rank = driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[4]/span')
    for i in rank:
        larat.append(i.text)
except NoSuchElementException:
    larat.append('-')
try:
    peak = driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[5]/span')
    for i in peak:
        perant.append(i.text)
except NoSuchElementException:
    perant.append('-')
try:
    weeks = driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[6]/span')
    for i in weeks:
        webot.append(i.text)
except NoSuchElementException:
    webot.append('-')

In [84]:
print(len(songt),len(larat))

100 100

In [91]:
df=pd.DataFrame({'Song Name':songt, 'Last week rank':larat,'Peak Rank':perant,'Weeks on board':webot})
df

                       Song Name Last week rank Peak Rank Weeks on board
0                     Last Night              1         1             28
1                       Fast Car              2         2             20
2                   Cruel Summer              4         3             14
3                      Calm Down              6         3             49
4                       Fukumean              7         4              8
..                           ...            ...       ...            ...
95                       Lagunas              -        77              6
96                     Overdrive             68        47              3
97  Bzrp Music Sessions, Vol. 55             99        31             10
98                         Dawns              -        42             15
99                       Rubicon              -        63              6

[100 rows x 4 columns]

In [98]:
#Q1
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [99]:
driver = webdriver.Chrome()

driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [103]:
rankt=[] 
namet=[] 
artist=[] 
updatet=[] 
viewt=[]

In [104]:
try:
    rank = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td')
    for i in rank:
        rankt.append(i.text)
except NoSuchElementException:
    rankt.append('-')

In [105]:
print(len(rankt))

380

In [106]:
#Q6
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By

In [107]:
driver = webdriver.Chrome()

driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-You")